export default {
    auth: {
        modal: {
            idle: {
                title: 'Your Session is About to Expire',
                content:
                    "You have been inactive for a while. For your security, we'll automatically sign you out in 5 minutes.",
                cancel: 'Log Out',
                ok: 'Continue Session',
            },
            expired: {
                title: 'Your session is expired, please log in <br /> again to use the platform.',
                ok: 'Login Again',
            },
        },
    },
    header: {
        welcome: 'Welcome',
        logo: 'ABC Supply Chain Partnership Program',
        profileName: 'Thai Fresh Fish Products Ltd.',
        dropdownMenu: {
            manageAccount: 'Manage Account',
            help: 'Help',
            termsAndConditions: 'Terms and Conditions',
            privacyPolicy: 'Privacy Policy',
            logout: 'Log out',
        },
        vendorName: 'Ascend Nano Co., Ltd.',
    },
    breadcrumbs: {
        _back: 'Back',
        dashboard: 'Dashboard',
        applications: 'Applications',
        linkAccount: 'Link Account',
        aboutUs: 'About ABC',
        introGuide: 'Introduction Guide',
        confirmYourDetails: 'Confirm Your Details',
        help: 'Help',
        myCustomers: 'My Customers',
        confirm: 'Confirm',
        notifications: 'Notifications',
        termsAndConditions: 'Terms and Conditions',
        privacyPolicy: 'Privacy Policy',
        supplyChainFinance: 'Supply Chain Finance',
        application: 'Application',
        supplyChainFinanceProduct: 'Supply Chain Finance Product Name',
        application_summary: 'APPLICATION SUMMARY',
        tnc: 'Terms and Condition',
        applicationDeclined: 'Application Canceled',
        applicationComplete: 'Application Complete',
        supplyChainFinanceSendOTP: 'OTP',
        applicationID: 'Application ID',
    },
    sidebar: {
        dashboard: 'Dashboard',
        applications: 'Applications',
        transactions: 'Transactions',
        tokens: 'Tokens',
        supplyChainFinance: 'Supply Chain Finance',
        myCustomers: 'My Customers',
        requests: 'Requests',
        pendingReview: 'Pending Review',
        approvedRejected: 'Approved/Rejected',
    },
    footer: {
        logo: 'ABC Supply Chain Partnership Program',
        copy: '© 2021 ABC Supply Chain Finance Partnership Program. All rights reserved',
    },
    pages: {
        applications: {
            heading: 'Applications',
        },
        dashboard: {
            linkYourAccount: {
                title: 'Link Your Customer Account to Access',
                content:
                    'Link your customer account to access the information.',
                cancel: 'Cancel',
                ok: 'Link Account',
            },
            pleaseRegisterForFinancing: {
                title: 'Please Register For Financing',
                content:
                    '“Transactions” is enabled only for suppliers that have successfully registered for financing with the financing entity of their choice.',
                cancel: 'Cancel',
                ok: 'Apply Now',
            },
            financingStatus: {
                product: 'Ascend Nano PREMIUM: Supply Chain Finance Product',
                viewSavedDraft: 'View Saved Draft',
                pendingReview: 'Pending Review',
                rejected: 'Rejected',
            },
            cancelStatus: {
                title: 'Are you sure you want to cancel your application?',
                subtitle:
                    'If you want to apply again, you will need to start from the start.',
                cancel: 'Cancel Application',
                ok: 'Keep Application',
            },
        },
        confirmDetails: {
            confirmYourDetails: 'Confirm Your Details',
            companyInformation: {
                title: 'Company Information',
                companyName: 'Company Name:',
                vendorNumber: 'Vendor Number:',
                taxId: 'Tax ID:',
            },
            contactInformation: {
                title: 'Contact Information',
                phoneNumber: 'Phone Number:',
                emailAddress: 'Email Address:',
                address: 'Address:',
            },
            note: 'Information is not updated?  Contact your Supplier Relationship Management Team.',
            cancel: 'Cancel',
            confirm: 'Confirm',
        },
        confirm: {
            success: {
                title: 'Your customer account is linked',
                subtitle:
                    'You can now register for financing with the financing entity of your choice and view products they <br/> offer. After successful registration, you can apply for financing based on the transactions sent by <br/> your customer!',
                backToDashboard: 'Back to Dashboard',
            },
            failed: {
                title: 'Unable to link your customer account',
                subtitle:
                    'An issue occurred with your account linkage. Please contact our customer <br/> support team or try again later.',
                backToDashboard: 'Back to Dashboard',
            },
        },
        transactions: {
            heading: 'Transactions',
        },
        help: {
            help: 'Help',
            faq: 'Frequently Asked Questions',
            contactUs: 'Contact Us',
        },
        myCustomersdata: {
            myCustomer: 'My Customers',
            companyName: 'Company Name',
            vendorNumber: 'Vendor Number',
            taxID: 'Tax ID',
            phoneNum: 'Phone Number',
            emailAdd: 'Email Address',
        },
        notifications: {
            heading: 'Notifications',
            MarkAsRead: 'Mark as read',
            Delete: 'Delete',
            Showing: 'Showing',
            ViewMore: 'View More',
            ViewLess: 'View Less',
            ReadNotif:
                'Read notifications after 30 days will be no longer be visible in the supplier portal',
            NoNotif: 'There are no notifications for now',
        },
        termsAndConditions: {
            heading: 'Terms and Conditions',
        },
        privacyPolicy: {
            heading: 'Privacy Policy',
            content:
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nibh nulla, lobortis ac ligula ut, congue facilisis orci. Pellentesque ac semper sem. Vivamus cursus a neque et sodales. Praesent ut ornare tortor. Cras fringilla est odio, non commodo tortor accumsan at. Proin tristique at ante sit amet sollicitudin. Phasellus sagittis nulla felis, sit amet lacinia mauris iaculis vel. Ut pharetra felis eget lacus molestie, nec dictum nunc venenatis. Integer efficitur augue dui, et ullamcorper tellus finibus in. Ut in consequat lorem. Nunc malesuada justo ac consequat ultrices. Vivamus porta tincidunt scelerisque. Cras porttitor mattis nunc, nec pretium urna pharetra id.\r\nNulla auctor ante nec pharetra maximus. Aliquam sollicitudin sapien nisi, sit amet imperdiet est blandit ut. Ut consequat aliquam est ac vehicula. Aenean tincidunt vestibulum risus, at vulputate tortor auctor vel. Nullam ex turpis, egestas sed malesuada in, rhoncus eleifend magna. Pellentesque sed dictum nulla, tempor tempus diam. Morbi id tristique leo, ac tristique ante. Etiam nec iaculis risus, sit amet auctor orci. Integer commodo id diam condimentum pulvinar. Nullam consequat, orci eget scelerisque iaculis, odio nisl vulputate nisi, nec tempor purus erat id enim. Duis porta id quam quis sodales. Donec aliquam vel ligula et ullamcorper. Duis sed urna eu est auctor porttitor. Donec porta ligula non sem laoreet facilisis.\r\nPhasellus nisi odio, porta ornare semper sed, volutpat sit amet lectus. Curabitur in diam accumsan, commodo odio gravida, consequat lacus. Phasellus maximus sodales purus nec congue. Sed condimentum, leo sed maximus rutrum, nunc quam dictum lectus, et luctus nunc dolor eget nisl. Sed porta eu elit at commodo. Nullam mollis velit ut elementum viverra. Suspendisse ac ipsum at justo elementum scelerisque.\r\nQuisque luctus ut tellus ac consectetur. Ut elit lorem, pharetra eu viverra nec, consequat tristique augue. Sed non nibh placerat, venenatis metus lobortis, semper magna. Etiam elementum dui neque, sit amet hendrerit lorem tristique eget. Nulla nec sodales turpis, ut volutpat orci. Vestibulum auctor sapien dolor, non efficitur libero dignissim sed. Suspendisse lobortis elit at nulla convallis, ac accumsan erat egestas. Fusce dapibus interdum erat, eu ultricies nibh suscipit in. Nullam faucibus eros ac lectus interdum efficitur. Praesent dapibus non erat ac congue.\r\nMauris accumsan tristique pretium. In vel sollicitudin enim. Aenean nisl purus, varius ac ultricies in, sagittis quis ex. Etiam lorem massa, rhoncus eget purus at, sodales accumsan lacus. Fusce congue dictum dolor. Integer in pellentesque erat. Maecenas accumsan velit neque, elementum ullamcorper mi volutpat vel. Mauris ut bibendum enim.',
        },
        supplyChainFinance: {
            applicationDate: 'Application Date',
            approvalDate: 'Approval Date',
            applicationRejectionDate: 'Application Rejection Date',
            savedDraftDate: 'Saved Draft Date',
            expiryDate: 'Expiry Date',
            learnMore: 'Learn More',
            status: {
                approved: 'Approved',
                rejected: 'Rejected',
                draft: 'Saved as Draft',
                pendingReview: 'Pending Review',
                unregistered:
                    'You don’t have any finance product. Go apply now!',
            },
            action: {
                viewDetails: 'View Details',
                viewSavedDraft: 'View Saved Draft',
                cancelApplication: 'Cancel Application',
            },
            supplyChainFinanceProduct: {
                applyButton: 'Apply Now',
                resumeButton: 'Resume',
            },
            supplyChainSendOTP: {
                scfSendOTP: 'OTP',
                enterCode: 'Enter your code',
                digits: 'We sent a 6-digit code to',
                email: 'wan***@***',
                ref: 'Ref: ABCD',
                confirm: 'Confirm',
                resend: 'Didn’t receive a code? Resend',
            },
            termsandconsent: {
                consent: 'Change Account Consent',
                terms: 'Terms & Conditions',
                termsAgree: 'I agree to the terms and conditions.',
                consentAgree: 'I agree to the Change Account Consent',
                caption:
                    'We will send an OTP to your email address to validate your acceptance of the Terms & Conditions and Change Account Consent',
                decline: 'Decline',
                sendOTP: 'Send OTP',
                decline_title:
                    'Do you want to decline T&Cs & Change Account Consent?',
                decline_subtitle:
                    'If you decline, your application will not be submitted.',
                yes: 'Yes',
                no: 'No',
            },
            applicationDeclined: {
                declined_title: 'Your finance application was not submitted',
                declined_subtitle:
                    'By declining the terms and conditions, your application has not been submitted. If you change your mind, we have saved your application as a draft and this can be submitted at a later time.',
                backToDashboard: 'Back to Dashboard',
            },
            applicationComplete: {
                complete_title:
                    'Your application for Supply Chain Finance has been successfully registered',
                complete_subtitle:
                    'Your Application ID for this submission is 123456, please keep note of this for reference. We will get back to you once your information has been processed. In the meantime, you can check the status of your application on the dashboard.',
                backToDashboard: 'Back to Dashboard',
            },
        },
        supplyChainFinanceRegister: {
            companyDetailsForm: {
                formTitle: 'Company Details',
                companyNameEN: 'Company name as per DBD (EN)',
                companyNameTH: 'Company name as per DBD (TH)',
                taxID: 'Tax ID',
                vendorCode: 'Vendor Number',
                vendorSiteNumber: 'Vendor site number',
                companyWebsite: 'Company Website (optional)',
                typeOfEntity: 'Type of entity',
                industry: 'Industry',
                businessType: 'Business Type',
                dateOfIncorporation: 'Date of Incorporation',
                numberOfEmployees: 'Number of Employees',
                country: 'Country',
                registeredCompanyAddress: 'Registered Company Address',
                provinces: 'Province',
                districts: 'District',
                subdistricts: 'Subdistrict',
                postalCode: 'Postal Code',
            },
            personalDetailsForm: {
                formTitle: 'Personal Details',
                formAccordionTitle: 'Authorised Director',
                firstNameEN: 'First Name (EN)',
                lastNameEn: 'Last Name (EN)',
                firstNameTH: 'First Name (TH)',
                lastNameTH: 'Last Name (TH)',
                nationality: 'Nationality',
                nationalIDcard: 'National ID Card Number',
                laserCode: 'Laser Code',
                passportNumber: 'Passport Number',
                dateOfBirth: 'Date of Birth',
                countryCode: 'Country Code',
                mobileNumber: 'Mobile Number',
                emailAddress: 'Email Address (optional)',
                jobTitle: 'Job Title (optional)',
                allocatedShares: '% of Allocated Shares (optional)',
                addAuthorizedDirector: 'Additional Authorized Director',
                removeAuthorizedDirector: 'Remove Authorised Director',
                removeDialog: {
                    title: 'Are you sure you want to remove?',
                    remove: 'Remove',
                    cancel: 'Cancel',
                },
            },
            stepper: [
                'Company Details',
                'Personal Details',
                'Shareholder Details',
                'Bank/Loan Information',
                'Upload Documents',
            ],
            continueBtn: 'Continue',
            prevBtn: 'Previous',
            caption: 'Clicking continue will automatically save your draft',
            errors: {
                required: 'Please Complete Field',
                invalidFormat: 'Invalid Format',
                minimumOf3Years:
                    'Invalid format. Company needs to have been operating for at least 3 years',
                mustBe20Years:
                    'Invalid Format. Authorized director cannot be less than 20 years old',
            },
            shareholderDetailsForm: {
                formTitle: 'Shareholder Details (Optional)',
                formsubTitle:
                    'If there are additional shareholders outside the authorized director(s) already listed in the previous section, please add required information for each shareholder that holds at least 20% of company shares.',
                addSHbutton: '+ Add Shareholder',
                shareHoldercount: 'Shareholder',
                removeShareHolder: 'Remove Shareholder',
                firstNameEN: 'First Name (EN)',
                lastNameEN: 'Last Name (EN)',
                firstNameTH: 'First Name (TH)',
                lastNameTH: 'Last Name (TH)',
                nationality: 'Nationalty',
                nationalIDcard: 'National ID Card Number',
                laserCode: 'Laser Code',
                passportNumber: 'Passport Number',
                allocatedShares: '% of Allocated Shares',
            },
            removeShareHolder: {
                title: 'Are you sure you want to remove?',
                cancel: 'Cancel',
                remove: 'Remove',
            },
            shareallocation: {
                title: 'Please revise share allocation',
                subtitle:
                    'The total % of allocated shares across the authorized director(s) and shareholder(s) listed in your application is more than 100% ',
                ok: 'Ok',
            },
            bankDetailsForm: {
                bankInformation: 'Bank/Loan Information',
                accountTypes: 'Account Type',
                accountHolderName: 'Account Holder Name',
                accountNumber: 'Account Number',
                bankName: 'Bank Name',
                provinces: 'Province',
                branchName: 'Branch Name',
                loanInformation: 'Loan Information',
                buyerCompanyName: 'Buyer Company Name',
                loanPurposes: 'Loan Purpose',
            },
            uploadDocumentForm: {
                title_upload: 'Uploaded Documents',
                title: 'Upload Document',
                subtitle:
                    ' *File must be in PDF, TIFF, JPG or PNG format and no more than 5 MB. Each upload will be saved to your application draft.',
                viewSamplebtn: 'View Sample',
                uploadBtn: 'Upload',
                id_authorised_title:
                    'Certified true copy of National ID card (FRONT & BACK) / Passport with current date',
                id_authorised:
                    '(Please upload this documentation for each authorised director listed in your application. Please also mask/hide the religion field of any National ID card uploaded)',
                id_shareholder_title:
                    'Certified true copy of National ID card (FRONT & BACK) / Passport of each shareholder',
                id_shareholder:
                    '(Please upload this documentation for each shareholder listed in your application.Please also mask/hide the religion field of any National ID card uploaded)',
                photo_authorised_title:
                    'Upload a live photo of authorized director taken with certified true copy of National ID card / Passport and current date',
                photo_authorised:
                    '(Please upload a live photo for each authorised director listed in your application.Please also mask/hide the religion field of any National ID card uploaded)',
                photo_business_property:
                    'Uploaded photo of the front of the business property with the company sign/logo',
                board_resolution_title: 'Company Board Resolution',
                board_resolution:
                    '(Please download two copies, upload one and at your earliest convenience, please also send a copy of the document to the address provided in the product details page)',
                downloadTemplate: 'Download Template Here',
                affidavit_title: 'Certified true copy of Company Affidavit',
                affidavit:
                    '(Please upload one and at your earliest convenience, please also send a copy of the document to the address provided in the product details page)',
                registries: 'Registries of Shareholders (BOJ.5 Form)',
                pp30: 'P.P.30 (6 months)',
                company_bank_book:
                    'Certified copy of the 1st page of Company’s bank book/statement (for disbursal)',
                optional: 'Optional',
                loa_title: 'Letter of authority',
                loa: '(Please download two copies, upload one and at your earliest convenience, please also send a copy of the document to the address provided in the product details page)',
                bank_statements: '6 months bank statements (operating a/c)',
                ncb: 'Directors’ NCB reports (credit bureau)',
                credit_report: 'Company’s credit report (credit bureau)',
                others: 'Other documents',
                downloadAll: 'Download All',
            },
            notApplicable: 'Not Applicable',
            placeholder: {
                not_applicable: 'No Details Input',
            },
            tncConsent: {
                title: 'T&C and Change Account Consent',
                subtitle: 'T&C and Change Account Consent accepted date',
                reject: 'Reject',
                approve: 'Approve',
                return: 'Return',
                approveTitle:
                    'Are you sure you want to approve the application?',
                rejectTitle: 'Are you sure you want to reject the application?',
                withdraw: 'Withdraw',
                withdrawTitle:
                    'Are you sure you want to withdraw the application?',
            },
        },
    },
    landing: {
        welcome_content: 'Welcome to the Finance Entity Portal',
        welcome_button: 'Sign up or log in',
        button_text: 'Sign up/Log in',
        first_section: {
            title: 'Strong trading relationships and a healthier supply chain',
            content:
                'Supply Chain Finance is a financial solution offered by CP Group, which allows you as a supplier to receive faster, early and efficient payments.',
            image: 'strong-trading-img-en',
        },
        second_section: {
            title: 'The next level in supply chain finance solutions',
            fast_title: 'Faster Payments',
            fast_content:
                'Receive faster payments of transactions and enjoy early payment options',
            block_title: 'Blockchain enabled',
            block_content:
                'We provide a blockchain-enabled and distributed network of trade finance and payment solutions to bring your business roaring into a new age of digital global trade.',
            fully_title: 'Fully Digitalized',
            fully_content:
                'Our supply chain finance solutions have been fully digitalized and allow you to log in and submit documents to manage payables online.',
        },
        third_section: {
            title: 'Future proof payment solutions',
            first_content:
                'Unlock operational excellence for your business through blockchain technology',
            second_content: 'Receive early access to cash at competitive rates',
            third_content: 'Enjoy an automated and quick onboarding process',
            image: 'future-proof-img-en',
        },
        fourth_section: {
            title: 'Join Us',
            content:
                'Become a part of ABC Supply Chain Finance Partnership Program and be part of the new standard in supply chain payment solutions today.',
        },
    },
    general_error: {
        internet: 'No internet connection. Please check and retry again.',
    },
    portal_content: {
        welcome_content: 'Welcome to Your Supply Chain Finance Portal',
        welcome_sub:
            'You can begin accessing your transactions by linking your customer accounts and then get started with registering for finance. ',
        button_content: 'Link Account',
        learn_more: 'Learn More',
        about_us: 'About ABC',
        intro: 'Introduction Guide',
    },
    supplier_link: {
        supplierlink_title: 'Please Link Your Account To Your Customer',
        supplierlink_sub: 'You are linking your account with:',
        buttonlink_content: 'Next',
    },
    error: {
        button_ok: 'OK',
        button_refresh: 'Refresh',
        button_back: 'Back',
        server_error: {
            title: 'Server Error',
            content:
                'An error occurred and your page could not be served. Please try again later.',
        },
    },
    finance: {
        finance_title1: 'Register for Finance Now',
        finance_sub2:
            'Your company is now eligible to apply for our Supply Chain Finance Program which provides SME’s access to early cash. Check out the financial products offered by our financing entity partner and apply now!',
        finance_title2: 'Ascend nano PREMIUM: ',
        finance_title3: 'Supply Chain Finance Product',
        finance_sub3:
            '• Apply for financing based on approved invoices sent by your customers.',
        finance_sub4: '• Digital and automated onboarding process.',
        finance_sub5:
            '• Access to early cash at competitive rates with Ascend Nano',
        financebtn_content: 'Apply Now',
    },
    financetab_approved: {
        financetab_title: 'Supply Chain Finance',
        financetab_title1: 'Your Finance Products',
        financetab_title2: 'Register for Finance',
        financetab_sub: 'New products coming soon!',
    },
    otp: {
        title: 'Enter your code',
        content: 'We sent a 6-digit code to',
        ref: 'Ref',
        enter_otp: 'Enter OTP',
        invalid: 'Invalid OTP. Please try again.',
        receive: 'Didn’t receive a code?',
        resend: 'Resend',
        button: 'Confirm',
        max_attempt:
            'Maximum attempts reached. You can only request for resending OTP after 15 minutes',
        required: 'This field is required.',
        enter_digit: 'Must be a 6-digit number',
        new_code: 'The new code has been sent to',
    },
    applications_page: {
        applications: 'Applications',
        registration_applications: 'Registration Applications',
        app_id: 'App ID',
        supplier: 'Supplier',
        product: 'Product',
        request_date: 'Request Date',
        status: 'Status',
        no_applications: 'There are no applications',
        pending: 'Pending',
        drafted: 'Drafted',
        approved: 'Approved',
        rejected: 'Rejected',
        withdrawn: 'Withdrawn',
    },
    pagination: {
        showing: 'Showing',
        rowsPerPage: 'Rows per page',
        of: 'of',
    },
    table_filter: {
        search: 'Search',
        searchData: 'Search data table below',
    },
    view_requests_page: {
        title: 'View Requests',
        request_id: 'Request ID',
        request_date: 'Request Date',
        total_funding_request: 'Total Funding Request',
        remaining_balance: 'Remaining Balance',
        currency: 'Currency',
        status: 'Status',
        product: 'Product',
        pending: 'Pending',
        drafted: 'Drafted',
        approved: 'Approved',
        rejected: 'Rejected',
        withdrawn: 'Withdrawn',
        pending_review: 'Pending review',
        no_requests_available: 'No requests available',
        no_records_found: 'Sorry, no matching records found',
    },
    request_pending_review: {
        title: 'Requests - Pending Review',
        req_id: 'Req ID',
        supplier: 'Supplier',
        request_date: 'Request Date',
        total_funding_request: 'Total Funding Request',
        remaining_balance: 'Remaining Balance',
        currency: 'Currency',
        approve: 'Approve',
        reject: 'Reject',
        export: 'Export',
        pending: 'Pending',
        drafted: 'Drafted',
        approved: 'Eligible',
        rejected: 'Ineligible',
        withdrawn: 'Withdrawn',
        pending_review: 'Pending review',
        no_requests_available: 'No requests available',
        no_records_found: 'Sorry, no matching records found',
        select_transactions: 'Please select transactions',
    },
    request_approved_rejected: {
        title: 'Requests - Approved/Rejected',
        req_id: 'Req ID',
        supplier: 'Supplier',
        request_date: 'Request Date',
        total_funding_request: 'Total Funding Request',
        remaining_balance: 'Remaining Balance',
        currency: 'Currency',
        status: 'Status',
        export: 'Export',
        pending: 'Pending',
        drafted: 'Drafted',
        approved: 'Approved',
        rejected: 'Rejected',
        withdrawn: 'Withdrawn',
        pending_review: 'pending review',
        no_requests_available: 'No requests available',
        no_records_found: 'Sorry, no matching records found',
        select_transactions: 'Please select transactions',
    },
    request_pop_up: {
        approve_title: 'Are you sure you want to approve the request?',
        reject_title: 'Are you sure you want to reject the request?',
        reason: 'Please input rejection reason',
        return: 'Return',
        reject: 'Reject',
        approve: 'Approve',
    },
    view_summary_page: {
        title: 'Request Summary',
        breadcrumbs: {
            eligibleForFinance: 'ELIGIBLE FOR FINANCE',
            viewSummary: 'REQUEST SUMMARY',
            request_submitted: 'REQUEST SUBMITTED',
            viewRequests: 'VIEW REQUESTS',
        },
        heading: 'Ascend Nano',
        subtitles: {
            request_date: 'Request Date',
            request_id: 'Request ID',
            status: 'Status',
            result_date: 'Result Date',
            supplier: 'Supplier'
        },
        confirm: 'Confirm',
        cancel: 'Cancel',
        transaction_id: 'Transction ID',
        transaction_amount: 'Transaction Amount',
        maturity_date: 'Maturity Date',
        currency: 'Currency',
        total: 'Total',
        advanced_payment: 'Advanced Payment Amount',
        financing_fees: 'Financing Fees',
        total_funding_request: 'Total Funding Request',
        remaining_balance: 'Remaining Balance',
        invoice_financing:
            'Your request for invoice financing is now <br /> pending review',
        descriptionOne:
            'Thank you for submitting your invoice financing request, this is now being processed by your <br /> chosen financing entity, your request ID is',
        descriptionTwo:
            'You can check the status of your request in  <br /> the View Requests tab or if you still have eligible invoices, you can continue requesting for finance <br />  on the Eligible for Finance tab.',
        btn: 'Back to Eligible for Finance',
        requestDate: 'Request Date',
        customer: 'Customer',
        reject: 'Reject',
        rejected: 'Rejected',
        approve: 'Approve',
        approved: 'Approved',
        approve_title: 'Are you sure you want to approve the request?',
        reject_title: 'Are you sure you want to reject the request?',
        reason: 'Please input rejection reason',
        return: 'Return',
        pending_review: 'Pending Review',
        rejection_reason: 'Rejection Reason'
    },
}
